server:
  port: 9000
  servlet:
    context-path: /api

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      table-prefix: Llj_

spring:
  application:
    name: ourBlog
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/blogDB?useUnicode=true&characterEncoding=UTF-8&serverTimeZone=UTC
  redis:
    host: 127.0.0.1
    port: 6379
  servlet:
    multipart:
      max-request-size: 20MB
      max-file-size: 2MB
